Import('env')

src = [
    "Client.cc",
    "ClientImpl.cc",
    "LeaderRPC.cc",
    "#build/proto/dlog.pb.o",
    "#build/proto/Client.o",
]

env.StaticLibrary("LogCabinClient",
                  src,
                  CPPPATH = [ "#" ])

