Import('env')

env.SharedObject("#build/test/gtest-all.o",
                 "#gtest/src/gtest-all.cc",
                 CPPPATH = [ "#gtest", "#gtest/include" ],
                 CPPFLAGS = [ "-g", "-DDEBUG" ],
                 CXXFLAGS = "-std=c++0x")
env.StaticLibrary("#build/test/gtest",
                 ["gtest-all.o"],
                 CPPPATH = [ "#gtest", "#gtest/include" ],
                 CPPFLAGS = [ "-g", "-DDEBUG" ],
                 CXXFLAGS = "-std=c++0x")
env.Program("test",
            [
              "TestRunner.cc",
              "dlogd/AsyncMutex.cc",
              "include/CommonTest.cc",
              "include/RefTest.cc",
              "libDLogStorage/DLogStorage.cc",
              "libDLogStorage/MemoryStorageModule.cc",
              "#build/dlogd/AsyncMutex.o",
              "#build/dlogd/Debug.o",
              "#build/libDLogStorage/DLogStorage.o",
              "#build/libDLogStorage/MemoryStorageModule.o",
            ],
            LIBPATH = [ "#build/test" ],
            LIBS = [ "gtest", "pthread", "protobuf", "rt" ],
            CPPPATH = ["#", "#include", "#gtest/include"],
            # -fno-access-control allows tests to access private members
            CXXFLAGS = env["CXXFLAGS"] + ["-fno-access-control"])
