Import('env')

env.SharedObject("#build/test/gtest-all.o",
                 "#gtest/src/gtest-all.cc",
                 CPPPATH = [ "#gtest", "#gtest/include" ],
                 CPPFLAGS = [ "-g", "-DDEBUG" ],
                 CXXFLAGS = "-std=c++0x")
env.StaticLibrary("#build/test/gtest",
                 ["gtest-all.o"],
                 CPPPATH = [ "#gtest", "#gtest/include" ],
                 CPPFLAGS = [ "-g", "-DDEBUG" ],
                 CXXFLAGS = "-std=c++0x")
env.Program("test",
            [
              "TestRunner.cc",
              "include/RefTest.cc",
            ],
            LIBPATH = [ "#build/test" ],
            LIBS = [ "gtest", "pthread" ],
            CPPPATH = ["#", "#include", "#gtest/include"])
