Import('env')

src = [
    "Address.cc",
    "Buffer.cc",
    "MessageSocket.cc",
    "TCPListener.cc",
]

env.StaticLibrary("LogCabinRPC",
                  src,
                  CPPPATH = [ "#" ])

