Import('env')

src = [
    "Address.cc",
    "Buffer.cc",
    "ClientSession.cc",
    "MessageSocket.cc",
    "OpaqueClientRPC.cc",
    "OpaqueServerRPC.cc",
    "ProtoBuf.cc",
    "Server.cc",
    "TCPListener.cc",
    "ThreadDispatchService.cc",
]

env.StaticLibrary("LogCabinRPC",
                  src,
                  CPPPATH = [ "#" ])

