Import('env')

src = [
    "Common.cc",
    "Checksum.cc",
    "Debug.c",
    "DLogRPC.cc",
    #"eventwrapper.cc",
]
env.StaticLibrary("DLogRPC",
                  src,
                  CPPPATH = [ "#include" ])

