Import('env')

src = [
    "Common.cc",
    "Checksum.cc",
    "Config.cc",
    "Debug.c",
    "DLogEchoService.cc",
    "DLogEvent.cc",
    "DLogEventLE2.cc",
    "DLogRPC.cc",
    "ProtoBuf.cc",
]
env.StaticLibrary("DLogRPC",
                  src,
                  CPPPATH = [ "#include" ])

