Import('env')

src = [
    "File.cc",
    "Internal.cc",
    "Loop.cc",
    "Signal.cc",
    "Timer.cc",
]

env.StaticLibrary("LogCabinEvent",
                  src,
                  CPPPATH = [ "#" ])

