Import('env')

env.Program("dlogperf", [ "main.cc" ],
            LIBPATH = [ "#build/libDLogRPC", "#build/libDLogClient" ],
            LIBS = [ "DLogRPC", "DLogClient" ],
            CPPPATH = "#include")

