Import('env')

src = [
    "#build/Protocol/Client.pb.o",
]

env.StaticLibrary("LogCabinProtocol",
                  src)

env.Protoc([],
           "Client.proto",
           PROTOCPROTOPATH = ['.'],
           PROTOCPYTHONOUTDIR = None,
           PROTOCOUTDIR = '.')

env.StaticObject("#build/Protocol/Client.pb.o",
                 "#build/Protocol/Client.pb.cc",
                 CXXFLAGS = "-std=c++0x")
