import os

opts = Variables('../../Local.sc')

opts.AddVariables(
    ("CC", "C Compiler"),
    ("AS", "Assembler"),
    ("LINK", "Linker"),
)

env = Environment(options = opts, tools = ['default'], ENV = os.environ)

env.Program("dlogd", [ "main.cpp" ],
	    LIBPATH = [ "#build/libDLogRPC" ],
	    LIBS = [ "DLogRPC" ],
	    CPPPATH = "#include",
            CFLAGS = "-g")

