Import('env')

src = [
    "main.cc",
    "AsyncMutex.cc",
    "LogManager.cc",
    "#build/proto/dlog.pb.o",
    "#build/dlogd/InternalLog.pb.o",
]

env.Program("dlogd", src,
            LIBPATH = [ "$LIBPATH",
                        "#.",
                        "#build/libDLogRPC",
                        "#build/libDLogStorage" ],
            LIBS = [ "event_core-2.0", "event_pthreads-2.0",
                     "protobuf", "DLogRPC", "DLogStorage", "rt" ],
            CPPPATH = [ "#include", "#" ])

env.Protoc([],
           "InternalLog.proto",
           PROTOCPROTOPATH = ['.'],
           PROTOCPYTHONOUTDIR = None,
           PROTOCOUTDIR = '.')

env.StaticObject("#build/dlogd/InternalLog.pb.o",
                 "#build/dlogd/InternalLog.pb.cc",
                 CPPPATH = "#",
                 CXXFLAGS = "-std=c++0x")
