Import('env', 'object_files')

src = [
    "ClientService.cc",
    "Globals.cc",
    "LogManager.cc",
]
object_files['Server'] = (env.StaticObject(src) +
                          env.Protobuf("InternalLog.proto"))
