Import('env')

env.Program("HelloWorld",
            ["HelloWorld.cc", "#build/liblogcabin.a"],
            LIBS = [ "pthread", "protobuf", "rt", "cryptopp",
                     "event_core", "event_pthreads" ])
