Import('env')

libs = [ "pthread", "protobuf", "rt", "cryptopp" ]

env.Program("Benchmark",
            ["Benchmark.cc", "#build/liblogcabin.a"],
            LIBS = libs)

env.Program("HelloWorld",
            ["HelloWorld.cc", "#build/liblogcabin.a"],
            LIBS = libs)

env.Program("Reconfigure",
            ["Reconfigure.cc", "#build/liblogcabin.a"],
            LIBS = libs)

env.Program("SmokeTest",
            ["SmokeTest.cc", "#build/liblogcabin.a"],
            LIBS = libs)
