Import('env')

libs = [ "pthread", "protobuf", "rt", "cryptopp",
         "event_core", "event_pthreads" ]

env.Program("HelloWorld",
            ["HelloWorld.cc", "#build/liblogcabin.a"],
            LIBS = libs)

env.Program("Reconfigure",
            ["Reconfigure.cc", "#build/liblogcabin.a"],
            LIBS = libs)

env.Program("SmokeTest",
            ["SmokeTest.cc", "#build/liblogcabin.a"],
            LIBS = libs)
