import os

opts = Variables('../../Local.sc')

opts.AddVariables(
    ("CC", "C Compiler"),
    ("CXX", "C++ Compiler"),
    ("AS", "Assembler"),
    ("LINK", "Linker"),
)

env = Environment(options = opts, tools = ['default'], ENV = os.environ)

src = [
    "DLogClient.cc",
]
env.StaticLibrary("DLogClient",
                  src,
                  CPPPATH = [ "#include" ],
                  CPPFLAGS = [ "-g", "-std=c++0x" ])

